### PR TITLE
fix toggle button

### LINKED ISSUE #293: [BUG]: toggle initialises in SGW
### Is there already an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

toggle intiallises in SGW making e2e test impossible 
even when user is in another position and lets say user clicks sgw and then recenter back to their postion the sgw toggle remians selcted 

### Expected Behavior

if the user is in the SGW then it should initiliase to SGW or if in loyola then it should initilise in Loyola otherwise it should not be initialised or selcted (either of the campuses)
when user is in another position and lets say user clicks sgw and then recenter back to their postion the sgw toggle should get unselcted 

### Steps To Reproduce

1. set user location to non campus point 
2. run the app

### Anything Else?

_No response_

### PR DESCRIPTION
**Pull request by das-bhaskar**
## Summary

fix bug issue for toggle initiliasation and removed some unused functions 

---

## Related Issue

Closes #293 

---

## How has this been tested?

- [ ] Unit tests
- [x] Manual testing
- [ ] End-to-end testing
- [ ] No test required

---

## Screenshots

Screenshot 2026-03-08 at 23 28 11

---

## Checklist

- [x] I have provided a summary of my changes
- [x] I have specified the PR related issues
- [x] I have tested implemented the required test for this code (if any)

---

### CODE REVIEW

File: app/src/main/java/com/example/myapplication/ui/viewmodel/MapViewModel.kt [hunk 1]
```diff
@@ -108,30 +101,37 @@ class MapViewModel(
...
-            if (uiBuildingState.selectedTransportMode == "shuttle" &&
-                uiBuildingState.startLocationName == "Your position") {
-                refreshShuttleStatus(userLocation)
-            }
+
         } else {
+            // BUG FIX: Logic for when user is NOT at a campus
             isManualCampusSelection = false
+            currentCampus = null // This unselects SGW/LOY buttons
+            highlightedBuildingName = null
```
Comment (20Mathieu03) [inline app/src/main/java/com/example/myapplication/ui/viewmodel/MapViewModel.kt]: Great this should make it so the initial state of both campus buttons is unselected.

Comment (das-bhaskar) [reply app/src/main/java/com/example/myapplication/ui/viewmodel/MapViewModel.kt]: yup!

**Review by 20Mathieu03 — APPROVED** [review]
Finally fixed :). e2e test for campus toggle button should pass now.
