### PR TITLE
Fix building highlight color and rendering glitch

### LINKED ISSUE #143: [BUG]: Current location campus building color.
### Is there already an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When the users current location is a campus building the color of the building is a darker shade of burgundy.

### Expected Behavior

When the users current location is a campus building, the color of the building should be yellow.

### Steps To Reproduce

1. Run the app.
2. Have the current location be a campus building.

### Anything Else?

_No response_

### PR DESCRIPTION
**Pull request by das-bhaskar**
## Summary

- Swapped building highlight color from burgundy to Concordia Gold (#FFD700).
- Set highlight fill opacity to 0.6 (alpha 153) per design request.
- Fixed the 1-second "blinking" glitch by adding a state check to prevent redundant map clearing.
- also removed MainActivity.kt it was redundant

---

## Related Issue

Fixes #143

---

## How has this been tested?

- [ ] Unit tests
- [x] Manual testing
- [ ] End-to-end testing
- [ ] No test required

---

## Screenshots
Screenshot 2026-02-16 at 20 57 16

---

## Checklist

- [x] I have provided a summary of my changes
- [x] I have specified the PR related issues
- [x] I have tested implemented the required test for this code (if any)

---

### CODE REVIEW

File: app/src/main/java/com/example/myapplication/logic/MapManager.kt [hunk 1]
```diff
@@ -75,17 +76,26 @@ class MapManager(private val googleMap: GoogleMap) {
         drawBuildings(campus, highlightedBuildingName)
     }
 
+    private var lastBuilding: String? = "NONE"
+
     private fun drawBuildings(campus: Campus, highlightedBuildingName: String?) {
+        if (highlightedBuildingName == lastBuilding) {
```
Comment (Kevin7582) [inline app/src/main/java/com/example/myapplication/logic/MapManager.kt]: "highlightedBuildingName" seems a bit long and too general for a variable name, change it for something more precise, preferably related to the functionnality of the variable like  "selectedBuildingName" or "activeBuildingName" for more clarity.

Comment (das-bhaskar) [reply app/src/main/java/com/example/myapplication/logic/MapManager.kt]: it will need to much refactoring which might complicate things; thanks for the suggestion though!
